### ISSUE TITLE
Plugin spams values between -1000 and 1000 into console

### ISSUE THREAD

**Issue by Querrin** [kadenscott/RandomSpawnPlus3#20]
**Describe the bug**
After removing plugins one by one, I have come to a conclusion that the latest build of RandomSpawnPlus (v3.4.2) spams values between 1000 and -1000 into the console without stopping.

**Server Info**
- Minecraft version: 1.15.2
- RSP version: v3.4.2
- Bukkit version & fork: Tested on PaperSpigot 1.15.2 (Build 264) and Spigot 1.15.2

**Configs**
- config.yml: Have not changed a thing
- spawns.yml: Have not changed a thing

**Comment by Querrin** [comment]
Forgot to add server log.
https://pastebin.com/dXAMebwi

**Comment by kadenscott** [comment]
Fixed this in 3.4.2, but I think I uploaded the wrong .jar to Spigot. Anyways, uploading a 3.4.3 soon which has the fix.
