### ISSUE TITLE
Cannot disable /wild

### ISSUE THREAD

**Issue by Averagess** [kadenscott/RandomSpawnPlus3#7]
Owner has tried disabling wild from the config but it still works, and default rank in groupmanager doesnt have permission to the node randomspawnplus.wild and they can still use it

**Comment by kadenscott** [comment]
I was originally going to leave this for the 3.4 release, but since its such a simple fix I'll be uploading a 3.3.3 version for this. Thank you for the bug report.

Also, side note (and completely unrelated) -- you should switch to LuckPerms, GM is very unsupported.

**Comment by Averagess** [comment]
Talk about fast response time, wow. Thank you, appreciate it.

**Comment by kadenscott** [comment]
No worries, I'm glad you're enjoying the plugin :^)
