### ISSUE TITLE
Changing spawnrange doesn't work

### ISSUE THREAD

**Issue by xlnd47** [kadenscott/RandomSpawnPlus3#8]
Changing the spawnrange keeps people spawning at default range. 
The server is running on 1.15.2-R0.1-SNAPSHOT

First I reloaded everything but nothing changed, so I restarted the server but nothing changed as well.

**Comment by xlnd47** [comment]
Found out these were the cached locations.

**Comment by kadenscott** [comment]
Yeah, I should probably add a disclaimer or something. Glad you fixed your issue :)
